# Service Account Definitions for AgentEngine
# Phase 3: Security & Production

# Service accounts follow the principle of least privilege
# Each service account has only the permissions needed for its function

service_accounts:
  # Agent Engine Runtime Service Account
  # Used by deployed agents in production
  - name: agent-engine-runtime
    display_name: "Agent Engine Runtime"
    description: "Service account for running Agent Engine workloads"
    roles:
      - roles/aiplatform.user           # Query Vertex AI models
      - roles/logging.logWriter         # Write logs to Cloud Logging
      - roles/cloudtrace.agent          # Send traces to Cloud Trace
      - roles/monitoring.metricWriter   # Write metrics to Cloud Monitoring

  # Agent Engine Deployer Service Account
  # Used by CI/CD to deploy agents
  - name: agent-engine-deployer
    display_name: "Agent Engine Deployer"
    description: "Service account for deploying Agent Engine resources"
    roles:
      - roles/aiplatform.admin          # Manage Agent Engine resources
      - roles/storage.objectViewer      # Read deployment artifacts
      - roles/iam.serviceAccountUser    # Act as runtime service account

  # Agent Engine Admin Service Account
  # Used for administrative operations
  - name: agent-engine-admin
    display_name: "Agent Engine Admin"
    description: "Service account for administrative operations"
    roles:
      - roles/aiplatform.admin          # Full Agent Engine access
      - roles/monitoring.admin          # Manage monitoring resources
      - roles/logging.admin             # Manage logging resources
      - roles/iam.securityAdmin         # Manage IAM policies

  # Agent Engine Viewer Service Account
  # Read-only access for monitoring
  - name: agent-engine-viewer
    display_name: "Agent Engine Viewer"
    description: "Read-only access to Agent Engine resources"
    roles:
      - roles/aiplatform.viewer         # View Agent Engine resources
      - roles/monitoring.viewer         # View metrics
      - roles/logging.viewer            # View logs

# Workload Identity Pool (for external systems)
workload_identity:
  pool_name: agent-engine-wi-pool
  display_name: "Agent Engine Workload Identity Pool"
  providers:
    # GitHub Actions provider for CI/CD
    - name: github-actions
      display_name: "GitHub Actions"
      issuer_uri: "https://token.actions.githubusercontent.com"
      attribute_mapping:
        google.subject: assertion.sub
        attribute.actor: assertion.actor
        attribute.repository: assertion.repository
      attribute_condition: |
        assertion.repository_owner == 'YOUR_GITHUB_ORG'

# IAM Conditions (for fine-grained access)
conditions:
  # Only allow access during business hours
  business_hours:
    title: "Business Hours Only"
    expression: |
      request.time.getHours("Asia/Seoul") >= 9 &&
      request.time.getHours("Asia/Seoul") < 18 &&
      request.time.getDayOfWeek("Asia/Seoul") >= 1 &&
      request.time.getDayOfWeek("Asia/Seoul") <= 5

  # Only allow from specific IP ranges
  corporate_network:
    title: "Corporate Network Only"
    expression: |
      request.auth.claims.email.endsWith("@your-domain.com")
