# GitHub Actions Production Deployment for AgentEngine
# Triggers on v* tag push

name: Deploy Production

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'AgentEngine/**'

defaults:
  run:
    working-directory: AgentEngine

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating releases
      id-token: write  # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            AgentEngine/.venv
          key: uv-${{ runner.os }}-${{ hashFiles('AgentEngine/pyproject.toml', 'AgentEngine/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Deploy to Production
        run: |
          source .venv/bin/activate
          echo "=== Deploying to production: ${{ steps.version.outputs.VERSION }} ==="
          python scripts/deploy_source.py --env production
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Register Version
        run: |
          source .venv/bin/activate
          echo "=== Registering version: ${{ steps.version.outputs.VERSION }} ==="
          python scripts/version/register.py --version ${{ steps.version.outputs.VERSION }}
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify Production Deployment
        run: |
          source .venv/bin/activate
          echo "=== Verifying production deployment ==="
          gcloud ai agent-engines list \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --location=asia-northeast3 \
            --format="table(name,displayName,state)"

      - name: Generate Release Notes
        id: release-notes
        run: |
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "## AgentEngine ${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### Deployment Info" >> $GITHUB_OUTPUT
          echo "- **Environment**: Production" >> $GITHUB_OUTPUT
          echo "- **Region**: asia-northeast3" >> $GITHUB_OUTPUT
          echo "- **Deployed at**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### Changes" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD 2>/dev/null || echo "- Initial release"
          echo "" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: AgentEngine ${{ steps.version.outputs.VERSION }}
          body: ${{ steps.release-notes.outputs.NOTES }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
